name: Make Windows Release From Pushed Version Tag
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    name: Windows Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: egor-tensin/setup-mingw@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.7
      - run: ./build.sh
        shell: bash
      - run: cp LICENSE.txt output/
        shell: bash
      - run: cp README.md output/
        shell: bash
      - uses: thedoctor0/zip-release@master
        with:
          type: zip
          directory: output
          filename: ../heic2png.zip
      - uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: true
          files: heic2png.zip
          generate_release_notes: true
