name: Run Tests
on: [pull_request]
jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - run: ./build.sh
        shell: bash
